// flow-typed signature: b195e4a541cf1f6bc228e9d099f36e11
// flow-typed version: <<STUB>>/onchange_v^6.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'onchange'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'onchange' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'onchange/cli' {
  declare module.exports: any;
}

declare module 'onchange/echo' {
  declare module.exports: any;
}

declare module 'onchange/test/concurrent' {
  declare module.exports: any;
}

declare module 'onchange/test/queue' {
  declare module.exports: any;
}

declare module 'onchange/test/scripts/slow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'onchange/cli.js' {
  declare module.exports: $Exports<'onchange/cli'>;
}
declare module 'onchange/echo.js' {
  declare module.exports: $Exports<'onchange/echo'>;
}
declare module 'onchange/index' {
  declare module.exports: $Exports<'onchange'>;
}
declare module 'onchange/index.js' {
  declare module.exports: $Exports<'onchange'>;
}
declare module 'onchange/test/concurrent.js' {
  declare module.exports: $Exports<'onchange/test/concurrent'>;
}
declare module 'onchange/test/queue.js' {
  declare module.exports: $Exports<'onchange/test/queue'>;
}
declare module 'onchange/test/scripts/slow.js' {
  declare module.exports: $Exports<'onchange/test/scripts/slow'>;
}
