// flow-typed signature: c9f6f6e4a14c40f5732e745db580f663
// flow-typed version: <<STUB>>/stylelint-config-rational-order_v^0.1.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-rational-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-rational-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-rational-order/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/borderInBoxModel' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/config/configCreator' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/config/extendedStylelintOrderConfig' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/animation' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/border' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/boxModel' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/misc' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/positioning' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/special' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/typography' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/groups/visual' {
  declare module.exports: any;
}

declare module 'stylelint-config-rational-order/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-rational-order/__tests__/index' {
  declare module.exports: $Exports<'stylelint-config-rational-order/__tests__'>;
}
declare module 'stylelint-config-rational-order/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/__tests__'>;
}
declare module 'stylelint-config-rational-order/borderInBoxModel.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/borderInBoxModel'>;
}
declare module 'stylelint-config-rational-order/config/configCreator.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/config/configCreator'>;
}
declare module 'stylelint-config-rational-order/config/extendedStylelintOrderConfig.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/config/extendedStylelintOrderConfig'>;
}
declare module 'stylelint-config-rational-order/groups/animation.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/animation'>;
}
declare module 'stylelint-config-rational-order/groups/border.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/border'>;
}
declare module 'stylelint-config-rational-order/groups/boxModel.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/boxModel'>;
}
declare module 'stylelint-config-rational-order/groups/misc.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/misc'>;
}
declare module 'stylelint-config-rational-order/groups/positioning.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/positioning'>;
}
declare module 'stylelint-config-rational-order/groups/special.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/special'>;
}
declare module 'stylelint-config-rational-order/groups/typography.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/typography'>;
}
declare module 'stylelint-config-rational-order/groups/visual.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/groups/visual'>;
}
declare module 'stylelint-config-rational-order/index' {
  declare module.exports: $Exports<'stylelint-config-rational-order'>;
}
declare module 'stylelint-config-rational-order/index.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order'>;
}
declare module 'stylelint-config-rational-order/plugin/index' {
  declare module.exports: $Exports<'stylelint-config-rational-order/plugin'>;
}
declare module 'stylelint-config-rational-order/plugin/index.js' {
  declare module.exports: $Exports<'stylelint-config-rational-order/plugin'>;
}
