// flow-typed signature: 4481d69fb92fb12d2c4dd3b4a2901dfc
// flow-typed version: <<STUB>>/@rebass/grid_v^6.1.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rebass/grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rebass/grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rebass/grid/babel.config' {
  declare module.exports: any;
}

declare module '@rebass/grid/dist/emotion' {
  declare module.exports: any;
}

declare module '@rebass/grid/dist' {
  declare module.exports: any;
}

declare module '@rebass/grid/emotion' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rebass/grid/babel.config.js' {
  declare module.exports: $Exports<'@rebass/grid/babel.config'>;
}
declare module '@rebass/grid/dist/emotion/index' {
  declare module.exports: $Exports<'@rebass/grid/dist/emotion'>;
}
declare module '@rebass/grid/dist/emotion/index.js' {
  declare module.exports: $Exports<'@rebass/grid/dist/emotion'>;
}
declare module '@rebass/grid/dist/index' {
  declare module.exports: $Exports<'@rebass/grid/dist'>;
}
declare module '@rebass/grid/dist/index.js' {
  declare module.exports: $Exports<'@rebass/grid/dist'>;
}
declare module '@rebass/grid/emotion.js' {
  declare module.exports: $Exports<'@rebass/grid/emotion'>;
}
