// @flow

export default function normalizeTitle(title: string): string {
  return title
    .replace('- 100% Remote ', '')
    .replace(' (100% Remote)', '')
    .replace(' | 100% Remote | ', '')
    .replace(' - 100% remote', '')
    .replace('-- 100% Remote, Flexible hours', '')
    .replace('-- 100% REMOTE, FLEXIBLE HOURS', '')
    .replace('- 100% REMOTE, FLEXIBLE HOURS', '')
    .replace(' - Onsite or Remote', '')
    .replace('Remote or On Site-', '')
    .replace('- Full remote', '')
    .replace(' (allows remote)', '')
    .replace(' ()', '')
    .replace('Sr ', 'Senior ')
    .replace('Sr. ', 'Senior ')
    .replace('Jr ', 'Junior ')
    .replace('Jr. ', 'Junior ')
    .replace(' (Rails/React)', '')
    .replace('(Remote)', '')
    .replace(' (remote)', '')
    .replace(' (REMOTE)', '')
    .replace(' [REMOTE]', '')
    .replace('REMOTE: ', '')
    .replace(' - [Remote]', '')
    .replace(' - Remote', '')
    .replace(' - remote', '')
    .replace('Full Time ', '')
    .replace(', Remote', '')
    .replace('/ Remote ', '')
    .replace(' - REMOTE', '')
    .replace('REMOTE ', '')
    .replace('(Go)', '')
    .replace('(UK/EU only)', '')
    .replace('(UK/EU Only)', '')
    .replace('Remote ', '')
    .replace(', remote-friendly ', '')
    .replace(' - Work From Home', '')
    .replace(', work from home', '')
    .replace(' work from home', '')
    .replace(' Remote/Homeoffice ', '')
    .replace('designer', 'Designer')
    .replace('Back-end', 'Backend')
    .replace('back-end', 'Backend')
    .replace('Back-End', 'Backend')
    .replace('Back End', 'Backend')
    .replace('Front-end', 'Frontend')
    .replace('Front End', 'Frontend')
    .replace('front-end', 'Frontend')
    .replace('Front-End', 'Frontend')
    .replace('Front end', 'Frontend')
    .replace('Full-Stack', 'Full Stack')
    .replace('Full stack', 'Full Stack')
    .replace(' JS ', ' Javascript ')
    .replace('Full-stack', 'Full Stack')
    .replace('developer', 'Developer')
    .replace('engineer', 'Engineer')
    .replace('IoS', 'iOS')
    .replace('IOs', 'iOS')
    .trim();
}
