// @flow

export default function normalizeTitle(title: string): string {
  return title
    .replace('- 100% Remote ', '')
    .replace(' (100% Remote)', '')
    .replace(' | 100% Remote | ', '')
    .replace(' - 100% remote', '')
    .replace('-- 100% Remote, Flexible hours', '')
    .replace('-- 100% REMOTE, FLEXIBLE HOURS', '')
    .replace('- 100% REMOTE, FLEXIBLE HOURS', '')
    .replace(' - Onsite or Remote', '')
    .replace('Remote or On Site-', '')
    .replace('- Full remote', '')
    .replace(' (allows remote)', '')
    .replace(' ()', '')
    .replace('Sr ', 'Senior ')
    .replace('Sr. ', 'Senior ')
    .replace(' (Rails/React)', '')
    .replace('(Remote)', '')
    .replace(' (remote)', '')
    .replace(' (REMOTE)', '')
    .replace(' [REMOTE]', '')
    .replace('REMOTE: ', '')
    .replace(' - [Remote]', '')
    .replace(' - Remote', '')
    .replace(', Remote', '')
    .replace('/ Remote ', '')
    .replace(' - REMOTE', '')
    .replace('REMOTE ', '')
    .replace('(Go)', '')
    .replace('(UK/EU only)', '')
    .replace('(UK/EU Only)', '')
    .replace('Remote ', '')
    .replace(', remote-friendly ', '')
    .replace(' - Work From Home', '')
    .replace(', work from home', '')
    .replace(' work from home', '')
    .replace(' Remote/Homeoffice ', '')
    .trim();
}
